# Generated by Django 4.1.5 on 2023-12-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managment", "0004_task_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default=""),
        ),
    ]
