# Generated by Django 4.1.5 on 2023-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managment", "0005_remove_profile_bio_userprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(default=""),
        ),
    ]
